# Generated by Django 6.1.1 on 2026-09-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DraftDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_key", models.CharField(db_index=True, max_length=255)),
                ("language", models.CharField(max_length=15)),
                ("content_id", models.PositiveBigIntegerField()),
                ("version_id", models.PositiveBigIntegerField(null=True)),
                ("texts_hash", models.CharField(max_length=64)),
                ("unaligned", models.JSONField(blank=True, default=list)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "draft delivery",
                "ordering": ["-delivered_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PluginKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("plugin_id", models.PositiveBigIntegerField(unique=True)),
                ("key", models.CharField(db_index=True, max_length=32)),
            ],
            options={
                "verbose_name": "plugin key",
            },
        ),
    ]
