# Generated by Django 6.1.1 on 2026-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_ponyglot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftdelivery",
            name="plugin_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
