# Generated by Django 6.1.1 on 2026-09-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0045_pageurl_site_unique_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teaser",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                ("link", models.URLField(blank=True)),
                (
                    "style",
                    models.CharField(choices=[("a", "A"), ("b", "B")], default="a", max_length=10),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
